tweaking ss_redosound and kittykuake

diff --git a/scripts/ss_redosound b/scripts/ss_redosound
--- a/scripts/ss_redosound
+++ b/scripts/ss_redosound
@@ -9,26 +9,36 @@
 #
 # TODO: check if kdialog is installed and notify action taken
 
+LOG_FILE="/tmp/scripts/ss_redosound.log"
 
 declare -A DEVICES
 DEVICES["01_80_DE_00_0A_F7"]="alias=OP3 codec=ldac_sq"
-DEVICES["AC_80_0A_77_BB_63"]="alias=W1k codec=ldac_sq"
-DEVICES["01_02_03_04_67_AC"]="alias=EN4 codec=ldac_sq"
+
+# DEVICES["AC_80_0A_77_BB_63"]="alias=W1k codec=ldac_hq"
+# DEVICES["AC_80_0A_77_BB_63"]="alias=W1k codec=ldac_mq"
+# DEVICES["AC_80_0A_77_BB_63"]="alias=W1k codec=ldac_sq"
+# DEVICES["AC_80_0A_77_BB_63"]="alias=W1k codec=sbc"
+DEVICES["AC_80_0A_77_BB_63"]="alias=W1k codec=sbc_xq_453"
+# DEVICES["AC_80_0A_77_BB_63"]="alias=W1k codec=sbc_xq_512"
+# DEVICES["AC_80_0A_77_BB_63"]="alias=W1k codec=sbc_xq_552"
+
+DEVICES["01_02_03_04_18_9D"]="alias=EN4 codec=ldac_sq" # Soundpeates Engine 4
 DEVICES["98_80_BB_40_CE_2D"]="alias=A4P codec=aptx"
 
-LOG_FILE="/tmp/ss_redosound.log"
-
-touch $LOG_FILE;
+sudo -H -u ccolorado bash -c mkdir -p /tmp/scripts/
+sudo -H -u ccolorado bash -c touch -m $LOG_FILE
 chmod a+rw $LOG_FILE
 
 # Function to check connected Bluetooth devices from pactl sinks
-echo $(date)" start ss_redosound" >> $LOG_FILE
+echo "[ START ss_redosound $(date)]" >> $LOG_FILE
 echo "0 $0" >> $LOG_FILE
 echo "1 $1" >> $LOG_FILE
 echo "2 $2" >> $LOG_FILE
 
 check_connected_device() {
-    local sink_list; sink_list=$(pactl list sinks | grep "bluez.path" | sort | uniq | cut -d= -f2)
+    local sink_list;
+    # sink_list=$(sudo -Hu ccolorado "pactl list sinks | grep "bluez.path" | sort | uniq | cut -d= -f2")
+    sink_list=$(pactl list sinks | grep "bluez.path" | sort | uniq | cut -d= -f2)
     local connected_device=""
 
     for device in "${!DEVICES[@]}"; do
@@ -46,19 +56,47 @@ check_connected_device() {
     fi
 }
 
+counter=0
+while true; do
+    echo ">> Looking for devices. Attempt $cunter" >> $LOG_FILE;
 
+    STATUS=$(pactl list sinks | grep -e "bluetooth.codec\|bluetooth.battery\|bluez.path" | sort | uniq)
+    CODEC_FIND_CMD=$(echo "$STATUS" | grep codec | tail -1 | cut -d'=' -f2)
+    CODEC_FIND_CMD=$(echo $CODEC_FIND_CMD | tr -d '"')
 
-STATUS=$(pactl list sinks | grep -e "bluetooth.codec\|bluetooth.battery\|bluez.path" | sort | uniq)
-CODEC_FIND_CMD=$(echo "$STATUS" | grep codec | tail -1 | cut -d'=' -f2)
-CODEC_FIND_CMD=$(echo $CODEC_FIND_CMD | tr -d '"')
+    BATTERY_FIND_CMD=$(echo "$STATUS" | grep battery | tail -1 | cut -d= -f2)
+    ADDRESS=$(check_connected_device)
 
-BATTERY_FIND_CMD=$(echo "$STATUS" | grep battery | tail -1 | cut -d= -f2)
+    # echo 59
+    # Debug running as root for udev
+    # STATUS=$(pactl list sinks )
+    # echo "status : $STATUS"
+    # echo "address : $ADDRESS"
+    # echo "devices : $DEVICES"
+    #
+    # echo 64
 
-ADDRESS=$(check_connected_device)
-touple="${DEVICES[$ADDRESS]}"
+    echo $ADDRESS
+    touple="${DEVICES[$ADDRESS]}"
+    ALIAS=$(echo $touple | cut -d\  -f1 | cut -d= -f2)
+    CODEC=$(echo $touple | cut -d\  -f2 | cut -d= -f2)
 
-ALIAS=$(echo $touple | cut -d\  -f1 | cut -d= -f2)
-CODEC=$(echo $touple | cut -d\  -f2 | cut -d= -f2)
+    if [ ! -z "${ALIAS}" ]; then  # if $ALIAS IS SET
+        echo "  DEVICE FOUND" >> $LOG_FILE
+        break;
+    fi
+
+    echo "DEVICE NOT FOUND. ATTEMPT $counter" >> $LOG_FILE; 
+
+    sleep 5
+    counter=$((counter+1))
+
+    if [[ "$counter" -gt 10 ]]; then
+        echo "EXAHUSTED ATTEMPTS" >> $LOG_FILE
+        exit 1
+    fi
+
+done
 
 echo "Alias : $ALIAS" >> $LOG_FILE;
 echo "ADDRESS : $ADDRESS" >> $LOG_FILE;
@@ -82,7 +120,7 @@ if [ $CODEC_FIND_CMD != "$CODEC" ]; then
   command="pactl send-message $SINK_SELECTOR switch-codec $CODEC"
   $command
 else
-  echo "Nothing to do";
+  echo "Nothing to do, Codec already set";
 fi
 
-echo "[$(date)] end ss_redosound" >> $LOG_FILE
+echo "[ END ss_redosound $(date)]" >> $LOG_FILE
